version: '3.0'

services:
  store_redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  redis_volume:
